services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - ./:/app
    restart: always
    environment:
      - PORT=8080
    command: go run main.go
